# Generated by Django 4.1.2 on 2023-04-16 12:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nscore', models.FloatField(validators=[django.core.validators.MaxValueValidator(3.5), django.core.validators.MinValueValidator(-4)])),
                ('escore', models.FloatField(validators=[django.core.validators.MaxValueValidator(3.5), django.core.validators.MinValueValidator(-3.5)])),
                ('oscore', models.FloatField(validators=[django.core.validators.MaxValueValidator(3.5), django.core.validators.MinValueValidator(-3.5)])),
                ('ascore', models.FloatField(validators=[django.core.validators.MaxValueValidator(3.5), django.core.validators.MinValueValidator(-3.5)])),
                ('cscore', models.FloatField(validators=[django.core.validators.MaxValueValidator(3.5), django.core.validators.MinValueValidator(-3.5)])),
                ('ethnicity', models.CharField(choices=[('White', 'White'), ('Other', 'Other'), ('Mixed-White/Black', 'Mixed-White/Black'), ('Asian', 'Asian'), ('Mixed-White/Asian', 'Mixed-White/Asian'), ('Black', 'Black'), ('Mixed-Black/Asian', 'Mixed-Black/Asian')], max_length=20)),
                ('impulsive', models.FloatField(validators=[django.core.validators.MaxValueValidator(3.0), django.core.validators.MinValueValidator(-3.0)])),
                ('drug_type', models.CharField(choices=[('coke', 'coke'), ('heroin', 'heroin'), ('mushroom', 'mushroom'), ('lsd', 'lsd')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_status', models.BooleanField(default=False)),
                ('consumption_status', models.CharField(default=None, max_length=10, null=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drug_consumption.datasettable')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=7)),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug_consumption.admin')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datasettable',
            name='datasetmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug_consumption.patient'),
        ),
    ]
